# Homework 06 - Data Preprocessing

This notebook loads a raw dataset, applies reusable cleaning functions, compares the original and cleaned data, documents assumptions, and saves the cleaned dataset to `data/processed/`.

In [1]:
from pathlib import Path
import sys

import pandas as pd

In [2]:
HOMEWORK_ROOT = Path.cwd().parent
DATA_RAW = HOMEWORK_ROOT / "data" / "raw"
DATA_PROCESSED = HOMEWORK_ROOT / "data" / "processed"
SRC_DIR = HOMEWORK_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from cleaning import fill_missing_median, drop_missing, normalize_data

print("Homework root:", HOMEWORK_ROOT)
print("Raw data folder exists:", DATA_RAW.exists())
print("Processed data folder exists:", DATA_PROCESSED.exists())

Homework root: /Users/devampatel/Documents/NYU/homework/homework06
Raw data folder exists: True
Processed data folder exists: True

## 1. Load Raw Dataset

This section loads the raw sample dataset from `data/raw/`.

In [3]:
raw_path = DATA_RAW / "loan_sample.csv"

df_raw = pd.read_csv(raw_path)

print("Shape:", df_raw.shape)
df_raw

Shape: (5, 4)

   applicant_id  income  loan_amount default_risk
0          1001   55000        12000          low
1          1002   72000        18000       medium
2          1003   41000         9000         high
3          1004   88000        25000          low
4          1005   62000        15000       medium

## 2. Create Missing Values for Cleaning Practice

The sample dataset does not contain missing values, so this section creates a copy with a few missing values to demonstrate the preprocessing functions.

In [4]:
df_working = df_raw.copy()

df_working.loc[1, "income"] = pd.NA
df_working.loc[3, "loan_amount"] = pd.NA

print("Missing values before cleaning:")
print(df_working.isna().sum())

df_working

Missing values before cleaning:
applicant_id    0
income          1
loan_amount     1
default_risk    0
dtype: int64

   applicant_id   income  loan_amount default_risk
0          1001  55000.0      12000.0          low
1          1002      NaN      18000.0       medium
2          1003  41000.0       9000.0         high
3          1004  88000.0          NaN          low
4          1005  62000.0      15000.0       medium

## 3. Apply Cleaning Functions

This section fills missing numeric values with medians, drops any remaining missing rows, and normalizes numeric columns.

In [5]:
numeric_columns = ["income", "loan_amount"]

df_cleaned = fill_missing_median(df_working, numeric_columns)
df_cleaned = drop_missing(df_cleaned)
df_cleaned = normalize_data(df_cleaned, numeric_columns)

print("Missing values after cleaning:")
print(df_cleaned.isna().sum())

df_cleaned

Missing values after cleaning:
applicant_id    0
income          0
loan_amount     0
default_risk    0
dtype: int64

   applicant_id    income  loan_amount default_risk
0          1001  0.297872     0.333333          low
1          1002  0.372340     1.000000       medium
2          1003  0.000000     0.000000         high
3          1004  1.000000     0.500000          low
4          1005  0.446809     0.666667       medium

## 4. Compare Original and Cleaned Data

This section compares missing values, shape, and numeric summaries before and after cleaning.

In [6]:
print("Original shape:", df_working.shape)
print("Cleaned shape:", df_cleaned.shape)

print("\nMissing values before cleaning:")
print(df_working.isna().sum())

print("\nMissing values after cleaning:")
print(df_cleaned.isna().sum())

print("\nOriginal numeric summary:")
display(df_working[numeric_columns].describe())

print("\nCleaned numeric summary:")
display(df_cleaned[numeric_columns].describe())

Original shape: (5, 4)
Cleaned shape: (5, 4)

Missing values before cleaning:
applicant_id    0
income          1
loan_amount     1
default_risk    0
dtype: int64

Missing values after cleaning:
applicant_id    0
income          0
loan_amount     0
default_risk    0
dtype: int64

Original numeric summary:

             income   loan_amount
count      4.000000      4.000000
mean   61500.000000  13500.000000
std    19706.175005   3872.983346
min    41000.000000   9000.000000
25%    51500.000000  11250.000000
50%    58500.000000  13500.000000
75%    68500.000000  15750.000000
max    88000.000000  18000.000000

Cleaned numeric summary:

         income  loan_amount
count  5.000000     5.000000
mean   0.423404     0.500000
std    0.364228     0.372678
min    0.000000     0.000000
25%    0.297872     0.333333
50%    0.372340     0.500000
75%    0.446809     0.666667
max    1.000000     1.000000

## 5. Assumptions

- Missing numeric values are filled with the median because the median is less affected by extreme values.
- Any remaining rows with missing values are dropped after median filling.
- Numeric columns are normalized with min-max scaling so they use a common 0 to 1 range.
- This sample dataset is small, so the goal is to demonstrate the preprocessing workflow rather than build a final model-ready dataset.

In [7]:
processed_path = DATA_PROCESSED / "loan_sample_cleaned.csv"

df_cleaned.to_csv(processed_path, index=False)

print("Saved cleaned dataset to:", processed_path)

Saved cleaned dataset to: /Users/devampatel/Documents/NYU/homework/homework06/data/processed/loan_sample_cleaned.csv